import { IOptions } from '@/components/commons/ApelieSelectBox';

const colorPallets: IOptions[] = [
  { value: '#aa2e25', label: 'Vermelho - 1' },
  { value: '#f44336', label: 'Vermelho - 2' },
  { value: '#f6685e', label: 'Vermelho - 3' },
  { value: '#a31545', label: 'Rosa - 1' },
  { value: '#e91e63', label: 'Rosa - 2' },
  { value: '#ed4b82', label: 'Rosa - 3' },
  { value: '#6d1b7b', label: 'Roxo - 1' },
  { value: '#9c27b0', label: 'Roxo - 2' },
  { value: '#af52bf', label: 'Roxo - 3' },
  { value: '#482880', label: 'Roxo Escuro - 1' },
  { value: '#673ab7', label: 'Roxo Escuro - 2' },
  { value: '#8561c5', label: 'Roxo Escuro - 3' },
  { value: '#2c387e', label: 'Anil - 1' },
  { value: '#3f51b5', label: 'Anil - 2' },
  { value: '#6573c3', label: 'Anil - 3' },
  { value: '#1769aa', label: 'Azul - 1' },
  { value: '#2196f3', label: 'Azul - 2' },
  { value: '#4dabf5', label: 'Azul - 3' },
  { value: '#0276aa', label: 'Azul Claro - 1' },
  { value: '#03a9f4', label: 'Azul Claro - 2' },
  { value: '#35baf6', label: 'Azul Claro - 3' },
  { value: '#008394', label: 'Ciano - 1' },
  { value: '#00bcd4', label: 'Ciano - 2' },
  { value: '#33c9dc', label: 'Ciano - 3' },
  { value: '#00695f', label: 'Verde Azulado - 1' },
  { value: '#009688', label: 'Verde Azulado - 2' },
  { value: '#33ab9f', label: 'Verde Azulado - 3' },
  { value: '#357a38', label: 'Verde - 1' },
  { value: '#4caf50', label: 'Verde - 2' },
  { value: '#6fbf73', label: 'Verde - 3' },
  { value: '#618833', label: 'Verde Claro - 1' },
  { value: '#8bc34a', label: 'Verde Claro - 2' },
  { value: '#a2cf6e', label: 'Verde Claro - 3' },
  { value: '#8f9a27', label: 'Lima - 1' },
  { value: '#cddc39', label: 'Lima - 2' },
  { value: '#d7e360', label: 'Lima - 3' },
  { value: '#b2a429', label: 'Amarelo - 1' },
  { value: '#ffeb3b', label: 'Amarelo - 2' },
  { value: '#ffef62', label: 'Amarelo - 3' },
  { value: '#b28704', label: 'Âmbar - 1' },
  { value: '#ffc107', label: 'Âmbar - 2' },
  { value: '#ffcd38', label: 'Âmbar - 3' },
  { value: '#b26a00', label: 'Laranja - 1' },
  { value: '#ff9800', label: 'Laranja - 2' },
  { value: '#ffac33', label: 'Laranja - 3' },
  { value: '#b23c17', label: 'Laranja Escuro - 1' },
  { value: '#ff5722', label: 'Laranja Escuro - 2' },
  { value: '#ff784e', label: 'Laranja Escuro - 3' },
];

export default colorPallets;
