import IStore from '@/types/interfaces/interface-store';

const storeData: IStore[] = [
  {
    productImageUrl: 'https://static.educalingo.com/img/pt/800/artesanato.jpg',
    title: 'Vaso1',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Erat velit scelerisque in dictum.',
    type: 'Artesanal',
    score: 5,
    price: 15,
    quantity: 1,
  },
  {
    productImageUrl: 'https://static.educalingo.com/img/pt/800/artesanato.jpg',
    title: 'Vaso2',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Erat velit scelerisque in dictum.',
    type: 'Artesanal',
    score: 5,
    price: 15,
    quantity: 1,
  },
  {
    productImageUrl: 'https://static.educalingo.com/img/pt/800/artesanato.jpg',
    title: 'Vaso3',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Erat velit scelerisque in dictum.',
    type: 'Artesanal',
    score: 5,
    price: 15,
    quantity: 1,
  },
  {
    productImageUrl: 'https://static.educalingo.com/img/pt/800/artesanato.jpg',
    title: 'Vaso4',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Erat velit scelerisque in dictum.',
    type: 'Artesanal',
    score: 5,
    price: 15,
    quantity: 1,
  },
  {
    productImageUrl: 'https://static.educalingo.com/img/pt/800/artesanato.jpg',
    title: 'Vaso5',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Erat velit scelerisque in dictum.',
    type: 'Artesanal',
    score: 5,
    price: 15,
    quantity: 1,
  },
  {
    productImageUrl: 'https://static.educalingo.com/img/pt/800/artesanato.jpg',
    title: 'Vaso6',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Erat velit scelerisque in dictum.',
    type: 'Artesanal',
    score: 5,
    price: 15,
    quantity: 1,
  },
  {
    productImageUrl: 'https://static.educalingo.com/img/pt/800/artesanato.jpg',
    title: 'Vaso7',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Erat velit scelerisque in dictum.',
    type: 'Artesanal',
    score: 5,
    price: 15,
    quantity: 1,
  },
  {
    productImageUrl: 'https://static.educalingo.com/img/pt/800/artesanato.jpg',
    title: 'Vaso8',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Erat velit scelerisque in dictum.',
    type: 'Artesanal',
    score: 5,
    price: 15,
    quantity: 1,
  },
  {
    productImageUrl: 'https://static.educalingo.com/img/pt/800/artesanato.jpg',
    title: 'Vaso9',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Erat velit scelerisque in dictum.',
    type: 'Artesanal',
    score: 5,
    price: 15,
    quantity: 1,
  },
  {
    productImageUrl: 'https://static.educalingo.com/img/pt/800/artesanato.jpg',
    title: 'Vaso10',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Erat velit scelerisque in dictum.',
    type: 'Artesanal',
    score: 5,
    price: 15,
    quantity: 1,
  },
  {
    productImageUrl: 'https://static.educalingo.com/img/pt/800/artesanato.jpg',
    title: 'Vaso11',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Erat velit scelerisque in dictum.',
    type: 'Artesanal',
    score: 5,
    price: 15,
    quantity: 1,
  },
];

export default storeData;
