import IApelieTheme from '@/types/interfaces/interface-apelie-theme';
import IStore from '@/types/interfaces/interface-store';

export const storeData: IStore[] = [
  {
    userPhoto: 'https://i1.wp.com/terracoeconomico.com.br/wp-content/uploads/2019/01/default-user-image.png?ssl=1',
    storeImageUrl: 'https://www.encontracampinas.com/wp-content/uploads/2015/03/lojas-de-artesanato-em-campinas-1426092333.jpg',
    name: 'Loja 1',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Erat velit scelerisque in dictum.',
    theme: 'Artesanal',
    score: 5,
  },
  {
    userPhoto: 'https://i1.wp.com/terracoeconomico.com.br/wp-content/uploads/2019/01/default-user-image.png?ssl=1',
    storeImageUrl: 'https://61brasilia.com/wp-content/uploads/2020/06/Foto-Agda-Carvalho_Setur-DF-6.jpeg',
    name: 'Loja 2',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Erat velit scelerisque in dictum.',
    theme: 'Artesanal',
    score: 5,
  },
  {
    userPhoto: 'https://i1.wp.com/terracoeconomico.com.br/wp-content/uploads/2019/01/default-user-image.png?ssl=1',
    storeImageUrl: 'https://i.pinimg.com/originals/cb/34/4c/cb344c3dc2365927b34e242866e829f6.jpg',
    name: 'Loja 3',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Erat velit scelerisque in dictum.',
    theme: 'Artesanal',
    score: 5,
  },
  {
    userPhoto: 'https://i1.wp.com/terracoeconomico.com.br/wp-content/uploads/2019/01/default-user-image.png?ssl=1',
    storeImageUrl: 'https://aberturasimples.com.br/wp-content/uploads/2018/02/loja-de-artesanato.jpg',
    name: 'Loja 4',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Erat velit scelerisque in dictum.',
    theme: 'Artesanal',
    score: 5,
  },
  {
    userPhoto: 'https://i1.wp.com/terracoeconomico.com.br/wp-content/uploads/2019/01/default-user-image.png?ssl=1',
    storeImageUrl: 'https://pinzon.com.br/wp-content/uploads/2021/03/loja-Artesanato-de-PE-Plaza-Shopping-1.jpeg',
    name: 'Loja 5',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Erat velit scelerisque in dictum.',
    theme: 'Artesanal',
    score: 5,
  },
  {
    userPhoto: 'https://i1.wp.com/terracoeconomico.com.br/wp-content/uploads/2019/01/default-user-image.png?ssl=1',
    storeImageUrl: 'https://www.encontracampinas.com/wp-content/uploads/2015/03/lojas-de-artesanato-em-campinas-1426092333.jpg',
    name: 'Loja 6',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Erat velit scelerisque in dictum.',
    theme: 'Artesanal',
    score: 5,
  },
  {
    userPhoto: 'https://i1.wp.com/terracoeconomico.com.br/wp-content/uploads/2019/01/default-user-image.png?ssl=1',
    storeImageUrl: 'https://61brasilia.com/wp-content/uploads/2020/06/Foto-Agda-Carvalho_Setur-DF-6.jpeg',
    name: 'Loja 7',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Erat velit scelerisque in dictum.',
    theme: 'Artesanal',
    score: 5,
  },
  {
    userPhoto: 'https://i1.wp.com/terracoeconomico.com.br/wp-content/uploads/2019/01/default-user-image.png?ssl=1',
    storeImageUrl: 'https://i.pinimg.com/originals/cb/34/4c/cb344c3dc2365927b34e242866e829f6.jpg',
    name: 'Loja 8',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Erat velit scelerisque in dictum.',
    theme: 'Artesanal',
    score: 5,
  },
  {
    userPhoto: 'https://i1.wp.com/terracoeconomico.com.br/wp-content/uploads/2019/01/default-user-image.png?ssl=1',
    storeImageUrl: 'https://aberturasimples.com.br/wp-content/uploads/2018/02/loja-de-artesanato.jpg',
    name: 'Loja 9',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Erat velit scelerisque in dictum.',
    theme: 'Artesanal',
    score: 5,
  },
  {
    userPhoto: 'https://i1.wp.com/terracoeconomico.com.br/wp-content/uploads/2019/01/default-user-image.png?ssl=1',
    storeImageUrl: 'https://pinzon.com.br/wp-content/uploads/2021/03/loja-Artesanato-de-PE-Plaza-Shopping-1.jpeg',
    name: 'Loja 10',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Erat velit scelerisque in dictum.',
    theme: 'Artesanal',
    score: 5,
  },
  {
    userPhoto: 'https://i1.wp.com/terracoeconomico.com.br/wp-content/uploads/2019/01/default-user-image.png?ssl=1',
    storeImageUrl: 'https://www.encontracampinas.com/wp-content/uploads/2015/03/lojas-de-artesanato-em-campinas-1426092333.jpg',
    name: 'Loja 11',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Erat velit scelerisque in dictum.',
    theme: 'Artesanal',
    score: 5,
  },
  {
    userPhoto: 'https://i1.wp.com/terracoeconomico.com.br/wp-content/uploads/2019/01/default-user-image.png?ssl=1',
    storeImageUrl: 'https://61brasilia.com/wp-content/uploads/2020/06/Foto-Agda-Carvalho_Setur-DF-6.jpeg',
    name: 'Loja 12',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Erat velit scelerisque in dictum.',
    theme: 'Artesanal',
    score: 5,
  },
  {
    userPhoto: 'https://i1.wp.com/terracoeconomico.com.br/wp-content/uploads/2019/01/default-user-image.png?ssl=1',
    storeImageUrl: 'https://i.pinimg.com/originals/cb/34/4c/cb344c3dc2365927b34e242866e829f6.jpg',
    name: 'Loja 13',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Erat velit scelerisque in dictum.',
    theme: 'Artesanal',
    score: 5,
  },
  {
    userPhoto: 'https://i1.wp.com/terracoeconomico.com.br/wp-content/uploads/2019/01/default-user-image.png?ssl=1',
    storeImageUrl: 'https://aberturasimples.com.br/wp-content/uploads/2018/02/loja-de-artesanato.jpg',
    name: 'Loja 14',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Erat velit scelerisque in dictum.',
    theme: 'Artesanal',
    score: 5,
  },
  {
    userPhoto: 'https://image.freepik.com/fotos-gratis/modelo-de-foto-bonita_1157-7654.jpg',
    storeImageUrl: 'https://pinzon.com.br/wp-content/uploads/2021/03/loja-Artesanato-de-PE-Plaza-Shopping-1.jpeg',
    name: 'Loja 15',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Erat velit scelerisque in dictum.',
    theme: 'Artesanal',
    score: 5,
  },
];

export const themeData: IApelieTheme[] = [
  {
    themeImage: 'https://image.freepik.com/fotos-gratis/modelo-de-foto-bonita_1157-7654.jpg',
    themeTitle: 'Theme1',
  },
  {
    themeImage: 'https://image.freepik.com/fotos-gratis/modelo-de-foto-bonita_1157-7654.jpg',
    themeTitle: 'Theme2',
  },
  {
    themeImage: 'https://image.freepik.com/fotos-gratis/modelo-de-foto-bonita_1157-7654.jpg',
    themeTitle: 'Theme3',
  },
  {
    themeImage: 'https://image.freepik.com/fotos-gratis/modelo-de-foto-bonita_1157-7654.jpg',
    themeTitle: 'Theme4',
  },
  {
    themeImage: 'https://image.freepik.com/fotos-gratis/modelo-de-foto-bonita_1157-7654.jpg',
    themeTitle: 'Theme5',
  },
  {
    themeImage: 'https://image.freepik.com/fotos-gratis/modelo-de-foto-bonita_1157-7654.jpg',
    themeTitle: 'Theme6',
  },
  {
    themeImage: 'https://image.freepik.com/fotos-gratis/modelo-de-foto-bonita_1157-7654.jpg',
    themeTitle: 'Theme7',
  },
  {
    themeImage: 'https://image.freepik.com/fotos-gratis/modelo-de-foto-bonita_1157-7654.jpg',
    themeTitle: 'Theme8',
  },
];
